// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2K-8XhD4GmMXIMlNnYP4vFpy_0Vp3nJA',
    appId: '1:103372056660:web:73532014d439d8c12925c1',
    messagingSenderId: '103372056660',
    projectId: 'fmsdb-e4283',
    authDomain: 'fmsdb-e4283.firebaseapp.com',
    storageBucket: 'fmsdb-e4283.firebasestorage.app',
    measurementId: 'G-PP79VLBEYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGvDaqtg-nkA0JWcuRiorsNhUcfUzW6yM',
    appId: '1:103372056660:android:f29274f131c036102925c1',
    messagingSenderId: '103372056660',
    projectId: 'fmsdb-e4283',
    storageBucket: 'fmsdb-e4283.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlO0xVAcH1aERCPJUTLUDo_wPK2SAZPWc',
    appId: '1:103372056660:ios:25c5546ccea51d2d2925c1',
    messagingSenderId: '103372056660',
    projectId: 'fmsdb-e4283',
    storageBucket: 'fmsdb-e4283.firebasestorage.app',
    androidClientId: '103372056660-ks1rj9uc5rnfh85abivchgm986o7caev.apps.googleusercontent.com',
    iosClientId: '103372056660-a2n27oknl503d7lehf4e5lb97cab8e1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.floodManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2K-8XhD4GmMXIMlNnYP4vFpy_0Vp3nJA',
    appId: '1:103372056660:web:262807c1c3b118982925c1',
    messagingSenderId: '103372056660',
    projectId: 'fmsdb-e4283',
    authDomain: 'fmsdb-e4283.firebaseapp.com',
    storageBucket: 'fmsdb-e4283.firebasestorage.app',
    measurementId: 'G-Z85BTDYZ5V',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlO0xVAcH1aERCPJUTLUDo_wPK2SAZPWc',
    appId: '1:103372056660:ios:25c5546ccea51d2d2925c1',
    messagingSenderId: '103372056660',
    projectId: 'fmsdb-e4283',
    storageBucket: 'fmsdb-e4283.firebasestorage.app',
    androidClientId: '103372056660-ks1rj9uc5rnfh85abivchgm986o7caev.apps.googleusercontent.com',
    iosClientId: '103372056660-a2n27oknl503d7lehf4e5lb97cab8e1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.floodManagementSystem',
  );

}